name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Assign reviewers
        uses: kenshir0fumi/auto-assign-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
            bluetree7878
            rhehfl
            dmsdnWkd1234
            chamjin
